### ISSUE TITLE
Key Confusion apply button not working

### ISSUE THREAD

**Issue by CheariX** [RUB-NDS/JOSEPH#12]
Short:

Key Confusion cannot be applied in "interception" window.

Long:

When Burp intercepts a request containing a JWT, I can apply attacks with JOSEPH.
If i choose "Key Confusion" with a JSON key, it is not updated when i press the apply button.
I only tried the JSON method, but different attack variants.
In the manual JOSEPH window, the payload is adjusted.

The apply button works for Signature Exclusion.

**Comment by Merenon** [comment]
I'm closing this now, assuming it is working correctly. If not, please feel free to reopen.
